version: '3.8'
services:
  app:
    profiles: [app]
    build: .
    ports:
      - '3000:3000'
    environment:
      TYPEORM_HOST: db
      TYPEORM_PORT: 5432
      TYPEORM_DATABASE: ${TYPEORM_DATABASE}
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
