name: 'Pull request check'

on: pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install deps'
        run: npm ci
      - name: 'Build'
        run: npm run build
      - name: 'Test'
        run: npm run test
