name: 'Push'

on:
  push:
    branches:
      - 'main'
jobs:
  unit-test:
    name: 'Build and test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci
          npm run build
          npm run test
  bump-version:
    name: 'Version bump'
    runs-on: ubuntu-latest
    needs: [unit-test]
    permissions:
      contents: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Version bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'ci: bump version to {{version}} [skip ci]'
  trigger-deploy-webhook:
    name: 'Trigger deploy'
    runs-on: ubuntu-latest
    needs: [bump-version]
    steps:
      - name: Webhook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.RENDER_DEPLOY_WEBHOOK }}
